### PR TITLE
Added a custom scrollbar

### PR DESCRIPTION
**Pull request by Itz-Hyperz**
This adds a more "Discord-styled" scrollbar to the pages.

**Before:**

**After:**

### CODE REVIEW

**Comment by ItzDerock** [comment]
will merge and release in a bit

**Comment by Itz-Hyperz** [comment]
okay :]

**Comment by Itz-Hyperz** [comment]
any updates on this?

**Comment by ItzDerock** [comment]
sorry for delay, been busy.
merged and will release when I fix #53

**Pull request merged**
